minor formatting

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -4,13 +4,11 @@ HOME=/data/data/com.termux/files/home
 BIN=/data/data/com.termux/files/usr/bin
 
 path=$(find "$HOME" -type d -name "Revancify")
-cp "$path/revancify" "$BIN/revancify" > /dev/null 2>&1
+cp "$path/revancify" "$BIN/revancify" >/dev/null 2>&1
 DATA=$HOME/revancify-data
 mkdir -p "$DATA"
 
-
-terminate()
-{
+terminate() {
     clear
     echo "Script terminated !!"
     tput cnorm
@@ -18,30 +16,25 @@ terminate()
 }
 trap terminate SIGTERM SIGINT SIGABRT
 
-if [ "$(getprop ro.product.cpu.abi)" = "armeabi-v7a" ]
-then
+if [ "$(getprop ro.product.cpu.abi)" = "armeabi-v7a" ]; then
     echo "CPU architecture \"armeabi-v7a\" of your device is not supported for patching."
     echo "You may get build errors."
     read -N 1 -s -r -p $'Press ENTER to CONTINUE or SPACE to EXIT...\n' key
-    if [ "$key" = " " ]
-    then
+    if [ "$key" = " " ]; then
         echo "Script terminated"
         exit
     fi
 fi
 
-theme=$(jq -r '.theme' "$DATA/settings.json" 2> /dev/null) 
+theme=$(jq -r '.theme' "$DATA/settings.json" 2>/dev/null)
 export DIALOGRC=$DATA/.dialogrc$theme
 
-checkdependencies()
-{
-    
-    if bins=$(ls "$BIN") && grep -q java <<< "$bins" && grep -q wget <<< "$bins" && grep -q tput <<< "$bins" && grep -q dialog <<< "$bins" && grep -q jq <<< "$bins" && ls "$DATA/.dialogrcLight" > /dev/null 2>&1 && ls "$DATA/.dialogrcDark" > /dev/null 2>&1 && ls "$DATA/.dialogrcDefault" > /dev/null 2>&1 && ls "$BIN/revancify" > /dev/null 2>&1 && ls "$HOME/storage" > /dev/null 2>&1
-    then
+checkdependencies() {
+
+    if bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$DATA/.dialogrcLight" >/dev/null 2>&1 && ls "$DATA/.dialogrcDark" >/dev/null 2>&1 && ls "$DATA/.dialogrcDefault" >/dev/null 2>&1 && ls "$BIN/revancify" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
         return 0
     else
-        if ping -c 1 google.com > /dev/null 2>&1
-        then
+        if ping -c 1 google.com >/dev/null 2>&1; then
             installdependencies
             checkdependencies
         else
@@ -52,28 +45,25 @@ checkdependencies()
     fi
 }
 
-installdependencies()
-{
+installdependencies() {
     clear
     echo "Installing dependencies..."
     sleep 1
     termux-setup-storage
     pkg update -y &&
-    pkg install openjdk-17 wget ncurses-utils dialog jq -y &&
-    cp revancify "$BIN/revancify"
+        pkg install openjdk-17 wget ncurses-utils dialog jq -y &&
+        cp revancify "$BIN/revancify"
     git config --global pull.rebase true
     wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_dark" -O "$DATA/.dialogrcDark"
     wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_light" -O "$DATA/.dialogrcLight"
     wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_default" -O "$DATA/.dialogrcDefault"
     sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties" &&
-    echo "Dependencies installed successfully."
+        echo "Dependencies installed successfully."
     return 0
 }
 
-checkrevancify()
-{
-    if cd "$path" > /dev/null 2>&1 
-    then
+checkrevancify() {
+    if cd "$path" >/dev/null 2>&1; then
         tput civis
         rm -rf ./*cache*
         return 0
@@ -81,24 +71,26 @@ checkrevancify()
         echo -e "\e[1;31mDo you want to install again?\e[0m"
         read -r -p "[Y/N]: " choice
         case "$choice" in
-        y|Y ) rm -rf "$path"
+        y | Y)
+            rm -rf "$path"
             git clone https://github.com/decipher3114/Revancify.git && revancify && exit
-        ;;
-        n|N ) echo "Removing revancify completely !!"
+            ;;
+        n | N)
+            echo "Removing revancify completely !!"
             sleep 0.5s
             rm "$BIN/revancify"
             echo "Successfully Uninstalled revancify."
             exit 0
-        ;;
-        ? ) echo "Invalid option !!"
+            ;;
+        ?)
+            echo "Invalid option !!"
             exit 1
-        ;;
+            ;;
         esac
     fi
 }
 
-help()
-{
+help() {
     echo -e "\e[1;34mrevancify\n\e[0m"
     echo -e "\e[1;33mUsage:\e[0m \e[1;32mrevancify [OPTION]\n\e[0m"
     echo -e "\e[1;33mOptions:\e[0m"
@@ -110,25 +102,29 @@ help()
     echo -e "\n\e[1;35mGithub repo: https://github.com/decipher3114/Revancify\nTelegram channel: https://t.me/revancify\nTelegram support group: https://t.me/revancifychat\e[0m"
 }
 
-
 case "$1" in
-    "-h" | "--help" ) help
-        exit 0
+"-h" | "--help")
+    help
+    exit 0
     ;;
-    "-n" ) flag="$1"
+"-n")
+    flag="$1"
     ;;
-    "-r" ) if ping -c 1 google.com > /dev/null 2>&1
-        then
-            cd "$path"/.. && rm -rf "$path" && git clone https://github.com/decipher3114/Revancify.git && revancify && exit
-        fi
+"-r")
+    if ping -c 1 google.com >/dev/null 2>&1; then
+        cd "$path"/.. && rm -rf "$path" && git clone https://github.com/decipher3114/Revancify.git && revancify && exit
+    fi
     ;;
-    "-o" ) :
+"-o")
+    :
     ;;
-    "" ) :
+"")
+    :
     ;;
-    * ) echo -e "\e[1;31mInvalid option: $1\n\e[0m"
-        help
-        exit 1
+*)
+    echo -e "\e[1;31mInvalid option: $1\n\e[0m"
+    help
+    exit 1
     ;;
 esac
 
@@ -136,31 +132,27 @@ checkrevancify
 dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: Checking...\nStatus: Checking..." 10 42
 checkdependencies
 status=Offline
-if ping -c 1 google.com > /dev/null 2>&1
-then
+if ping -c 1 google.com >/dev/null 2>&1; then
     status=Online
 fi
-if [ "$1" == "-o" ]
-then
+if [ "$1" == "-o" ]; then
     status="Offline [forced]"
 fi
-if [ "$status" == "Online" ]
-then
-    git pull > /dev/null 2>&1 || ( git fetch --all > /dev/null 2>&1 && git reset --hard @{u} > /dev/null 2>&1 )
+if [ "$status" == "Online" ]; then
+    git pull >/dev/null 2>&1 || (git fetch --all >/dev/null 2>&1 && git reset --hard @{u} >/dev/null 2>&1)
     dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: $status" 10 42
 else
     dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: $status" 10 42
 fi
-cd "$DATA"  > /dev/null 2>&1 || :
+cd "$DATA" >/dev/null 2>&1 || :
 bash "$path/main.sh" "$flag"
 exitstatus=$?
 clear
 cd "$HOME" || :
-if [ $exitstatus -eq 0 ]
-then
+if [ $exitstatus -eq 0 ]; then
     echo "Script exited !!"
 else
     echo "Script terminated !!"
-    rm -rf -- *cache > /dev/null 2>&1
+    rm -rf -- *cache >/dev/null 2>&1
 fi
 tput cnorm
