chore: options compatiblity and configs updated

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -65,17 +65,18 @@ trap terminate SIGTERM SIGINT SIGABRT
 DATA="$HOME/revancify-data"
 [ ! -d $DATA ] && mkdir -p "$DATA"
 theme=$(jq -r '.theme' "$DATA/settings.json" 2>/dev/null)
-export DIALOGRC=$DATA/.dialogrc$theme
+theme=${theme:-Dark}
+export DIALOGRC="$path/configs/.dialogrc$theme"
 
 checkdependencies() {
-    if bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$DATA/.dialogrcLight" >/dev/null 2>&1 && ls "$DATA/.dialogrcDark" >/dev/null 2>&1 && ls "$DATA/.dialogrcDefault" >/dev/null 2>&1 && ls "$BIN/revancify" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
+    if bins=$(ls "$BIN") && grep -q java <<<"$bins" && grep -q wget <<<"$bins" && grep -q tput <<<"$bins" && grep -q dialog <<<"$bins" && grep -q jq <<<"$bins" && ls "$BIN/revancify" >/dev/null 2>&1 && ls "$HOME/storage" >/dev/null 2>&1; then
         return 0
     else
         if ping -c 1 google.com >/dev/null 2>&1; then
             installdependencies
             checkdependencies
         else
-            cp revancify "$BIN/revancify"
+            cp ./revancify "$BIN/revancify"
             echo "Dependencies not installed. Run again with internet connection."
             exit 1
         fi
@@ -85,27 +86,26 @@ checkdependencies() {
 installdependencies() {
     clear
     echo "Installing dependencies..."
+    cp ./revancify "$BIN/revancify"
     sleep 1
-    termux-setup-storage
+    [ ! -d "$HOME/storage" ] && termux-setup-storage
     pkg update -y
     pkg install openjdk-17 wget ncurses-utils dialog jq -y
-    cp revancify "$BIN/revancify"
     git config --global pull.rebase true
-    wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_dark" -O "$DATA/.dialogrcDark"
-    wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_light" -O "$DATA/.dialogrcLight"
-    wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc_default" -O "$DATA/.dialogrcDefault"
     sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties"
     echo "Dependencies installed successfully."
     return 0
 }
 
 checkrevancify() {
-    if cd "$path" >/dev/null 2>&1; then
+    if [ -d "$path" ]; then
         tput civis
+        cd "$path" >/dev/null 2>&1 || true
         rm -rf ./*cache*
         return 0
     else
-        echo -e "\e[1;31mDo you want to install again?\e[0m"
+        echo -e "\e[1;31mRevancify dir is not found !!\e[0m"
+        echo -e "\e[1;31mDo you want to reinstall Revancify?\e[0m"
         read -r -p "[Y/N]: " choice
         case "$choice" in
         y | Y)
@@ -129,7 +129,7 @@ checkrevancify() {
 
 checkrevancify
 checkdependencies
-dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: Checking...\nStatus      : Checking..." 10 42
+dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : Checking...\nStatus       : Checking..." 10 42
 status=Offline
 if ping -c 1 google.com >/dev/null 2>&1; then
     status=Online
@@ -139,11 +139,11 @@ if [ "$1" == "-o" ]; then
 fi
 if [ "$status" == "Online" ]; then
     git pull >/dev/null 2>&1 || (git fetch --all >/dev/null 2>&1 && git reset --hard "@{u}" >/dev/null 2>&1)
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus      : $status" 10 42
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
 else
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus      : $status" 10 42
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper    : decipher\nLast Updated : $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus       : $status" 10 42
 fi
-cd "$DATA" >/dev/null 2>&1 || :
+cd "$DATA" >/dev/null 2>&1 || true
 bash "$path/main.sh" "$flag"
 exitstatus=$?
 clear
