fix: report invalid args

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -7,21 +7,34 @@ path=$(find "$HOME" -type d -name "Revancify")
 cp "$path/revancify" "$BIN/revancify" >/dev/null 2>&1
 
 help() {
-    [ "$1" == "1" ] && echo -e "\e[1;31mInvalid Option(s) Passed!!\n\e[0m\n"
+    if [ "$1" == "1" ]; then
+        readarray -t invalidArgs < <(for i in "${FLAG_ERR[@]}"; do
+            if grep -q "unrecognized" <<< "$i"; then
+                grep -oP "(?<=\`).*(?=')" <<< "$i"
+            else
+                cut -b 27 <<< "$i" | xargs -0 -I {} echo -n "-{}"
+            fi
+        done)
+        IFS=","
+        echo -e "\e[1;31mInvalid Argument(s) Passed: ${invalidArgs[*]}\n\e[0m"
+    fi
     echo -e "\e[1;34mrevancify\n\e[0m
 \e[1;33mUsage:\e[0m \e[1;32mrevancify [OPTION]\n\e[0m
 \e[1;33mOptions:\e[0m
-\e[1;33m-n,--no-root     \e[1;34mRun without SU permissions\e[0m
-\e[1;33m-o,--offline     \e[1;34mRun without updating revancify\e[0m
-\e[1;33m-r,--reinstall   \e[1;34mReinstall revancify\e[0m
-\e[1;33m-h,--help        \e[1;34mPrints help statement\e[0m
+\e[1;33m-n, --no-root     \e[1;34mRun without SU permissions\e[0m
+\e[1;33m-o, --offline     \e[1;34mRun without updating revancify\e[0m
+\e[1;33m-r, --reinstall   \e[1;34mReinstall revancify\e[0m
+\e[1;33m-h, --help        \e[1;34mPrints help statement\e[0m
 
 \e[1;35mGithub repo: https://github.com/decipher3114/Revancify\nTelegram channel: https://t.me/revancify\nTelegram support group: https://t.me/revancifychat\e[0m"
     exit "$1"
 }
 
-VALID_ARGS=$(getopt -q -o nohr -l no-root,offline,help,reinstall -- "$@") || help 1
-eval set -- "$VALID_ARGS"
+if ! ARGS=$(getopt -o nohr -l "no-root,offline,help,reinstall" -- "$@" 2>/dev/null); then
+    readarray -t FLAG_ERR < <(getopt -o nohr -l no-root,offline,help,reinstall -- "$@" 2>&1 1>&-)
+    help 1
+fi
+eval set -- "$ARGS"
 while [ $# -gt 0 ]
 do
     case "$1" in
