Beautified Revancify

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -20,33 +20,58 @@ checkdependencies()
     then
         return 0
     else
-        return 1
+        if ping -c 1 google.com > /dev/null 2>&1
+        then
+            installdependencies
+            checkdependencies
+        else
+            cp revancify "$PATH/revancify"
+            echo "Dependencies not installed. Run again with internet connection."
+            exit 1
+        fi
     fi
 }
 
 installdependencies()
 {
+    clear
     echo "Installing dependencies..."
-    sleep 0.5s
-    git pull
+    sleep 1
     pkg update -y &&
     pkg install python openjdk-17 wget ncurses-utils dialog jq -y &&
     pip install wheel &&
     pip install requests bs4
-    grep -q decipher "$HOME/.dialogrc" > /dev/null 2>&1 || wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc" -O "$HOME/.dialogrc"
+    cp revancify "$PATH/revancify"
+    wget -q "https://raw.githubusercontent.com/decipher3114/MyConfigs/main/.dialogrc" -O "$HOME/.dialogrc"
     sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties" &&
     echo "Dependencies installed successfully."
+    return 0
 }
 
 checkrevancify()
 {
     if cd "$path" > /dev/null 2>&1 
     then
-        startup=(dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')" 9 42)
+        tput civis
+        rm -rf ./*cache*
         return 0
     else
-        echo "Revancify is not installed"
-        exit
+        echo -e "\e[1;31mDo you want to install again?\e[0m"
+        read -r -p "[Y/N]: " choice
+        case "$choice" in
+        y|Y ) rm -rf "$path"
+            git clone https://github.com/decipher3114/Revancify.git && revancify && exit
+        ;;
+        n|N ) echo "Removing revancify completely !!"
+            sleep 0.5s
+            rm "$PATH/revancify"
+            echo "Successfully Uninstalled revancify."
+            exit 0
+        ;;
+        ? ) echo "Invalid option !!"
+            exit 1
+        ;;
+        esac
     fi
 }
 
@@ -58,7 +83,6 @@ help()
     echo -e "\e[1;33m-n         \e[1;34mRun revancify as non root in rooted device\e[0m"
     echo -e "\e[1;33m-f         \e[1;34mForce update check for resources on startup\e[0m"
     echo -e "\e[1;33m-r         \e[1;34mReinstall revancify\e[0m"
-    echo -e "\e[1;33m-u         \e[1;34mUninstall or remove revancify\e[0m"
     echo -e "\e[1;33m-h,--help  \e[1;34mPrints help statement\e[0m"
     echo -e "\n\e[1;35mGithub repo: https://github.com/decipher3114/Revancify\nTelegram channel: https://t.me/revancify\nTelegram support group: https://t.me/revancifychat\e[0m"
 }
@@ -71,23 +95,20 @@ do
     ;;
     "-n" | "-f" ) arg="$1"
     ;;
+    "-c" ) echo -e "\e[1;31mAre you sure you want to clean resources?\e[0m"
+        echo -e "\e[1;31mThis will delete the CLI, patches and integrations for the current selected source.\e[0m"
+        read -r -p "[Y/N]: " choice
+        case "$choice" in
+        y|Y ) arg="$1"
+        ;;
+        ? ) :
+        ;;
+        esac
+    ;;
     "-r" ) if ping -c 1 google.com > /dev/null 2>&1
         then
             cd "$path"/.. && rm -rf "$path" && git clone https://github.com/decipher3114/Revancify.git && revancify && exit
         fi
-    ;;
-    "-u" ) echo -e "\e[1;31mAre you sure you want to uninstall revancify?\e[0m"
-        read -r -p "[Y/N]: " choice
-        case "$choice" in
-        y|Y ) rm -rf "$path"
-            rm "$PATH/revancify"
-            echo "Successfully Uninstalled revancify."
-            exit 0
-        ;;
-        ? ) echo "Uninstall Cancelled"
-            exit 1
-        ;;
-        esac
     ;;
     * ) echo -e "\e[1;31mInvalid option: $1\n\e[0m"
         help
@@ -97,42 +118,21 @@ do
     shift
 done
 
+checkrevancify
+checkdependencies
 if ping -c 1 google.com > /dev/null 2>&1
 then
-    checkrevancify
-    if checkdependencies
+    if [ "$arg" == "-f" ]
     then
-        tput civis
-        "${startup[@]}"
-        rm -rf ./*cache
-        git checkout . > /dev/null 2>&1
-        git config --global pull.rebase true
-        git pull > /dev/null 2>&1
-        dialog --keep-window --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')" 9 42
-        sleep 0.5
-        cp revancify "$PATH/revancify"
-        bash main.sh "$arg"
-    else
-        cp revancify "$PATH/revancify"
-        installdependencies &&
-        tput civis &&
-        "${startup[@]}"
-        bash main.sh "$arg"
-        cd "$HOME" || :
+        git fetch --all > /dev/null 2>&1
+        git reset --hard origin/main > /dev/null 2>&1
     fi
+    (git pull && cp revancify "$PATH/revancify") 2>&1 | dialog --no-collapse --no-shadow --progressbox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\n              by decipher\n         CONNECTED TO INTERNET" 20 42
+    tput civis
+    sleep 0.5
+    
 else
-    checkrevancify
-    if checkdependencies
-    then
-        tput civis &&
-        rm -rf ./*cache
-        tput civis &&
-        "${startup[@]}"
-        sleep 2
-        bash main.sh "$arg"
-        cd "$HOME" || :
-    else
-        cp revancify "$PATH/revancify"
-        echo "Dependencies not installed. Run again with internet connection."
-    fi
+    sleep 2 | dialog --no-collapse --no-shadow --progressbox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\n              by decipher\n       NOT CONNECTED TO INTERNET" 20 42 && tput civis
 fi
+bash main.sh "$arg"
+cd "$HOME" || :
