feat: add Extras Menu

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -13,6 +13,7 @@ terminate()
 {
     clear
     echo "Script terminated !!"
+    tput cnorm
     exit 1
 }
 trap terminate SIGTERM SIGINT SIGABRT
@@ -29,7 +30,7 @@ then
     fi
 fi
 
-theme=$(cat "$DATA/.theme")
+theme=$(jq -r '.theme' "$DATA/settings.json" 2> /dev/null) 
 export DIALOGRC=$DATA/.dialogrc$theme
 
 checkdependencies()
@@ -104,10 +105,7 @@ help()
     echo -e "\e[1;33mOptions:\e[0m"
     echo -e "\e[1;33m-n               \e[1;34mRun revancify as non root\e[0m"
     echo -e "\e[1;33m                 \e[1;34min rooted device"
-    echo -e "\e[1;33m-d [OPT],        \e[1;34mDelete the specified component\e[0m"
-    echo -e "\e[1;33m --delete [OPT]  \e[1;34mOPT: resources, apps, toml\e[0m"
-    echo -e "\e[1;33m-f               \e[1;34mForce update check for resources\e[0m"
-    echo -e "\e[1;33m                 \e[1;34mon startup\e[0m"
+    echo -e "\e[1;33m-o               \e[1;34mRun revancify offline (no update)\e[0m"
     echo -e "\e[1;33m-r               \e[1;34mReinstall revancify\e[0m"
     echo -e "\e[1;33m-h,--help        \e[1;34mPrints help statement\e[0m"
     echo -e "\n\e[1;35mGithub repo: https://github.com/decipher3114/Revancify\nTelegram channel: https://t.me/revancify\nTelegram support group: https://t.me/revancifychat\e[0m"
@@ -115,68 +113,47 @@ help()
 
 
 case "$1" in
-"-h" | "--help" ) help
-    exit 0
-;;
-"-n" | "-f" ) flag="$1"
-;;
-"-d" | "--delete" ) case "$2" in
-        "resources" ) echo -e "\e[1;31mAre you sure you want to delete resources(CLI, patches, integrations)\nfor currently selected source?\e[0m"
-        ;;
-        "apps" ) echo -e "\e[1;31mAre you sure you want to delete all downloaded apps?\e[0m"
-        ;;
-        "toml" ) echo -e "\e[1;31mAre you sure you want to delete the options.toml file?\e[0m"
-        ;;
-        "" ) echo -e "\e[1;31mNo Option specified !!\n\e[0m"
-            echo -e "\e[1;33mAllowed Options: resources, apps, toml\n\e[0m"
-            exit 1
-        ;;
-        * ) echo -e "\e[1;31mInvalid option: $2\n\e[0m"
-            echo -e "\e[1;33mAllowed Options: resources, apps, toml\n\e[0m"
-            exit 1
-        ;;
-        esac
-        read -r -p "[Y/N]: " choice
-        case "$choice" in
-        y|Y ) flag="$1" 
-            arg="$2"
-        ;;
-        ? ) :
-        ;;
-        esac
-;;
-"-r" ) if ping -c 1 google.com > /dev/null 2>&1
-    then
-        cd "$path"/.. && rm -rf "$path" && git clone https://github.com/decipher3114/Revancify.git && revancify && exit
-    fi
-;;
-"" ) :
-;;
-* ) echo -e "\e[1;31mInvalid option: $1\n\e[0m"
-    help
-    exit 1
-;;
+    "-h" | "--help" ) help
+        exit 0
+    ;;
+    "-n" ) flag="$1"
+    ;;
+    "-r" ) if ping -c 1 google.com > /dev/null 2>&1
+        then
+            cd "$path"/.. && rm -rf "$path" && git clone https://github.com/decipher3114/Revancify.git && revancify && exit
+        fi
+    ;;
+    "-o" ) :
+    ;;
+    "" ) :
+    ;;
+    * ) echo -e "\e[1;31mInvalid option: $1\n\e[0m"
+        help
+        exit 1
+    ;;
 esac
 
 checkrevancify
 dialog --keep-window --no-shadow --keep-window --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: Checking...\nStatus: Checking..." 10 42
 checkdependencies
-sleep 1
+status=Offline
 if ping -c 1 google.com > /dev/null 2>&1
 then
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: Online" 10 42
-    if ! git pull > /dev/null 2>&1
-    then
-        git fetch --all > /dev/null 2>&1
-        git reset --hard @{u} > /dev/null 2>&1
-    fi
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: Online" 10 42
+    status=Online
+fi
+if [ "$1" == "-o" ]
+then
+    status="Offline [forced]"
+fi
+if [ "$status" == "Online" ]
+then
+    git pull > /dev/null 2>&1 || ( git fetch --all > /dev/null 2>&1 && git reset --hard @{u} > /dev/null 2>&1 )
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: $status" 10 42
 else
-    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: Offline" 10 42
-    sleep 2
+    dialog --no-shadow --infobox "\n  █▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█\n  █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░  \n\nDeveloper   : decipher\nLast Updated: $(git log -1 --pretty='format:%cd' --date=format:'%b %d, %Y | %H:%M')\nStatus: $status" 10 42
 fi
 cd "$DATA"  > /dev/null 2>&1 || :
-bash "$path/main.sh" "$flag" "$arg"
+bash "$path/main.sh" "$flag"
 exitstatus=$?
 clear
 cd "$HOME" || :
